application: heidihaupiano-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /flash
  static_dir: flash
- url: /scripts
  static_dir: scripts
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /.*
  script: main.application
